kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: net-exporter
  namespace: {{ .Values.exporter.namespace }}
  labels:
    app: net-exporter
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: net-exporter
  template:
    metadata:
      labels:
        app: net-exporter
      annotations:
        releasetime: {{ $.Release.Time }}
    spec:
      initContainers:
      - name: label-kube-system-namespace
        {{ if (.Values.Installation) }}
        image: "{{ .Values.Installation.V1.Registry.Domain }}/{{ .Values.namespaceLabeler.image.name }}"
        {{ else }}
        image: "{{ .Values.image.registry }}/{{ .Values.namespaceLabeler.image.name }}"
        {{ end }}
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
      ## In our Control Plane net-exporter runs on monitoring ns
      ## By design Kubernetes does not allow to run critical pods
      ## having Priority Class like system-node-critical out of
      ## the namespace kube-system
      ##
      ## In the TC, net-exporter runs on kube-system and so this is fine
      {{ if (.Values.Installation) }}
      priorityClassName: giantswarm-critical
      {{ else }}
      priorityClassName: system-node-critical
      {{ end }}
      containers:
      - name: net-exporter
        {{ if (.Values.Installation) }}
        image: "{{ .Values.Installation.V1.Registry.Domain }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        {{ else }}
        image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        {{ end }}
        args:
        - "-namespace={{ .Values.exporter.namespace }}"
        - "-timeout={{ .Values.timeout }}"
        {{- range $key, $value := .Values.exporter.extraArgs }}
        - "-{{ $key }}={{ $value }}"
        {{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 5
        resources:
          # cpu limits removed so that throttling doesn't cause any unwanted
          # side-effects to measurements.
          requests:
            cpu: 50m
            memory: 75Mi
          limits:
            memory: 75Mi
      serviceAccountName: net-exporter
      securityContext:
        runAsUser: {{ .Values.userID }}
        runAsGroup: {{ .Values.groupID }}
      tolerations:
      # Tolerate all taints for observability
      - operator: "Exists"
