apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: net-exporter
  labels:
    app: net-exporter
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  resourceNames:
  - net-exporter
  - {{ .Values.dns.service }}
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - namespaces
  resourceNames:
  - kube-system
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ .Values.name }}
  verbs:
  - "use"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: net-exporter
  labels:
    app: net-exporter
subjects:
- kind: ServiceAccount
  name: net-exporter
  namespace: {{ .Values.exporter.namespace }}
roleRef:
  kind: ClusterRole
  name: net-exporter
  labels:
    app: net-exporter
  apiGroup: rbac.authorization.k8s.io
