name: net-exporter
namespace: monitoring

userID: 1000
groupID: 1000

port: 8000

dns:
  port: 1053
  label: coredns
  service: coredns

timeout: 5s

image:
  registry: quay.io
  name: giantswarm/net-exporter
  tag: [[ .SHA ]]

kubectl:
  image:
    registry: quay.io
    name: giantswarm/docker-kubectl
    tag: 1.16.4

# Control-plane subnets used to generate network policies
# for managed applications.
controlPlaneSubnets: []
